# Generated by Django 4.1.1 on 2022-09-07 19:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('level', wagtail.blocks.ChoiceBlock(choices=[('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6')])), ('title', wagtail.blocks.CharBlock())])), ('paragraph', wagtail.blocks.RichTextBlock()), ('staff', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('job_title', wagtail.blocks.CharBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('biography', wagtail.blocks.RichTextBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
